Documentation of Source Code
arpitghura/typing-test pull request #109
Opened 2023-02-05 13:16 UTC by aviiciii

### Code Documentation
To make the code easier for other developers to comprehend, I have provided brief descriptions of the code snippets in the HTML, CSS, and Javascript files.

This pull request solves #91 .

**Code Snippets:**
### HTML:
![d2](https://user-images.githubusercontent.com/88141521/216821049-38ed1e79-d086-4c88-ad9a-9e50d3a98ac8.png)
![d3](https://user-images.githubusercontent.com/88141521/216821054-75fc9581-b916-4c2f-b6c3-969f97f10ffb.png)
### Javascript:
![d1](https://user-images.githubusercontent.com/88141521/216821062-9c209444-6466-41ef-8d17-5c9d90505bd4.png)

2023-02-05 18:42 UTC, arpitghura requested changes
You also not added the comments in `testimonials.css`

2023-02-05 18:42 UTC, arpitghura commented on assets/js/dark.js
> +}
Fix the spacing

2023-02-06 11:24 UTC, aviiciii commented on assets/js/dark.js
> +}
Done both the tasks successfully.

2023-02-06 11:25 UTC, aviiciii commented
@arpitghura I have completed the requested reviews and commited to this pull request. Kindly review the changes and accept the pull request if no further changes are required.

2023-02-08 12:08 UTC, arpitghura approved these changes
looks good

2023-02-08 12:09 UTC, arpitghura commented
Do resolve the merge conflicts. If you face any issue, I am happy to help.

2023-02-08 15:13 UTC, aviiciii commented
@arpitghura I have resolved all merge conflicts. Kindly proceed with the pull request merge.

2023-02-08 19:39 UTC, arpitghura requested changes
The icons in Navigation menu are not visible on practice page. Have a look at this issue.
![image](https://user-images.githubusercontent.com/41796013/217633960-a9ced324-551b-46a0-a4f7-d6d9be9b9a65.png)

Do the required changes and let me know if you need any help.

2023-02-09 15:16 UTC, aviiciii commented
@arpitghura I have fixed the navigation bar icons. Kindly accept the pull request.

2023-02-09 17:22 UTC, merged