Final Readme.md file
arpitghura/typing-test pull request #17
Opened 2022-10-13 17:17 UTC by iharshka

Hey @arpitghura 
This is the final commit from my side, give your input also if there is a need for more changes to the readme.md file.
Regards.
Harsh

2022-10-14 04:08 UTC, arpitghura requested changes
Make changes as requested and also create badges from the [https://shields.io/](https://shields.io/) and don't copy and paste the badges from some other repo.

2022-10-14 04:08 UTC, arpitghura commented on README.md
> +![Typing test](https://img.shields.io/badge/Hacktoberfest-2022-blue?style=round-square&logo=Hacktoberfest&logoColor=black&link=https://hacktoberfest.com/)
Create all the badges from [https://shields.io/](https://shields.io/) and make badge in `for-the-badge` style. 

Use these credentials:
Username: `arpitghura`
repo name: `typing-test`

2022-10-14 08:01 UTC, iharshka commented on README.md
> +[![Typing Test](https://img.shields.io/badge/Typing-Test-brightgreen.svg?style=flat-square)](https://makeapullrequest.com)
Which one?

2022-10-14 08:03 UTC, iharshka commented
> Make changes as requested and also create badges from the https://shields.io/ and don't copy and paste the badges from some other repo.

I have just taken a reference, thanks for sharing the link.

2022-10-14 08:55 UTC, iharshka commented
Hey @arpitghura,
I have added the requested changes in this commit.
Changes- Moved the badges to the top, added for-the-badge style, added credentials, updated links of the badges.
Please check and do let me know.
regards

2022-10-15 18:47 UTC, arpitghura commented on README.md
> +#### Regards,</br>
Don't write these. 
Delete all after regards.

2022-10-15 18:47 UTC, arpitghura requested changes
Delete after regards as taught

2022-10-16 08:32 UTC, iharshka commented
I have made the requested changes. Please check it @arpitghura

2022-10-16 09:44 UTC, arpitghura approved these changes
Good work

2022-10-16 09:44 UTC, merged

2022-10-16 20:13 UTC, iharshka commented
Thanks arpit