Added average speed and time in history section.
arpitghura/typing-test pull request #48
Opened 2022-10-30 08:15 UTC by alexsam29

This PR is intended to resolve #44.

I added avg time and speed to both history sections in the practice and profile pages.

## Code Changes
- Added new table below existing history table to display averages
- In `showHistory()` added new table row element creation for the avg table.
- Added new variables in `showHistory()` to calculate average times.
- Simplified `innerHTML` string for the existing table with new variables.
- Added additional CSS to match new table with the existing table.

2022-10-30 10:27 UTC, arpitghura requested changes
Do the required change

2022-10-30 10:27 UTC, arpitghura commented on index.js
> +        avgTime = (avgTime / historyArray.length).toFixed(3);;
Remove double occurrence of `;`

2022-10-30 10:27 UTC, arpitghura commented on profile.js
> +        avgTime = (avgTime / historyArray.length).toFixed(3);;
remove double occurrence of semicolon

2022-10-30 21:52 UTC, alexsam29 commented
> Do the required change

Sorry, I fixed it.

2022-10-31 08:51 UTC, arpitghura approved these changes

2022-10-31 09:13 UTC, merged