Testmonial section added
arpitghura/typing-test pull request #65
Opened 2022-12-10 20:49 UTC by Riya14-dangra

I have added a testmonial section 
Please have a look on it
![Screenshot (98)](https://user-images.githubusercontent.com/84792579/206874709-3d0bf99e-5bcc-4800-8eec-7a841b4ef3ef.png)
Hope you my contribution Thank you!!

2022-12-11 15:18 UTC, Riya14-dangra commented
> I have added a testmonial section Please have a look on it ![Screenshot (98)](https://user-images.githubusercontent.com/84792579/206874709-3d0bf99e-5bcc-4800-8eec-7a841b4ef3ef.png) Hope you my contribution Thank you!!

@arpitghura please have a look if any change then please let me know

2022-12-11 15:31 UTC, arpitghura requested changes
Create a new page named `testimonials.html` and add these testimonials there. Also create a separate CSS file for this.

2022-12-11 15:32 UTC, Riya14-dangra commented
> Create a new page named `testimonials.html` and add these testimonials there. Also create a separate CSS file for this.

Okay

2022-12-11 15:35 UTC, arpitghura commented
Since we don't have any testimonials currently. so, whenever we have them, we will add them on the page. The page still be available in the repository, but no linking is to be done to this page currently.

2022-12-11 15:40 UTC, Riya14-dangra commented
> Since we don't have any testimonials currently. so, whenever we have them, we will add them on the page. The page still be available in the repository, but no linking is to be done to this page currently.

@arpitghura you mean that i only have to add the code not to display it or link it right na

2022-12-11 15:43 UTC, arpitghura commented
> > Since we don't have any testimonials currently. so, whenever we have them, we will add them on the page. The page still be available in the repository, but no linking is to be done to this page currently.
> 
> @arpitghura you mean that i only have to add the code not to display it or link it right na

Yeah, you have to write code that works perfectly fine, but the only thing is that if we make this page live with dummy content, will not look professional. so, when we have min. 2 testimonial then we will make the page live.

2022-12-12 15:06 UTC, Riya14-dangra commented
@arpitghura I have made a changes according you said to me please have look
Thank you!!

2022-12-12 19:37 UTC, arpitghura requested changes
Remove the testimonials from index.html and also remove the corresponding CSS, and so the required changes.

2022-12-12 19:37 UTC, arpitghura commented on testimonials.html
> +    <title>Document</title>
Change the title of the website to `Testimonials - Typing Test`

2022-12-12 19:37 UTC, arpitghura commented on testimonials.html
> +    <div class="testimonial" id="testimonials">
Add Navigation Menu similar to `index.html`.
You can just copy-paste the nav bar html and link index.css to testimonial.html

2022-12-12 21:57 UTC, Riya14-dangra commented
> Remove the testimonials from index.html and also remove the corresponding CSS, and do the required changes.

All required changes done please have a look @arpitghura 
Thank you!!

2022-12-13 06:51 UTC, arpitghura requested changes

2022-12-13 06:51 UTC, arpitghura commented on testimonials.html
> +        </div>
Add link to  `index.js` so that the navigation drop-down bar menu works on smartphones also.

2022-12-13 06:51 UTC, arpitghura commented on testimonials.html
> +    <link rel="stylesheet" href="./assets/css/testimonials.css">
Add `boxicon` css file link here so that GitHub logo in the navBar will be visible. The link is available in index.html file.

2022-12-13 06:51 UTC, arpitghura commented on index.html
> +    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
Remove these 4 lines ( 10, 11, 12, 13 ) that you have added.

2022-12-13 08:36 UTC, Riya14-dangra commented
@arpitghura please have a look I have done the changes as you suggest
Thank you!!

2022-12-13 11:52 UTC, arpitghura requested changes
Remove line number `9` as index.css is already linked.
and link the boxicon stylesheet that you removed from the `index.html` file as stated.

2022-12-13 11:52 UTC, arpitghura commented on index.html
> -    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
Do not remove this stylesheet from `index.html`

2022-12-13 11:52 UTC, arpitghura commented on index.html
> +    <link rel="stylesheet" href="assets/css/index.">
remove this line as the `index.css` is already present.

2022-12-14 15:31 UTC, Riya14-dangra commented
@arpitghura please have a look

2022-12-14 17:15 UTC, arpitghura commented
good work @Riya14-dangra

2022-12-14 17:16 UTC, merged