changed ui of about section
arpitghura/typing-test pull request #92
Opened 2023-02-02 16:47 UTC by niladrix719

2023-02-03 12:34 UTC, arpitghura reviewed
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project.

2023-02-03 12:36 UTC, arpitghura commented
Hey, create an issue for this PR and also provide the details if you are contributing through any event.

2023-02-04 20:41 UTC, arpitghura requested changes

2023-02-04 20:41 UTC, arpitghura commented on about.html
>              Typing Test is an open-source project created by <i>Arpit Ghura</i>.
Make `Typing Test` bold

2023-02-05 05:15 UTC, niladrix719 commented
@arpitghura Made it bold and highlighted

2023-02-05 18:13 UTC, arpitghura requested changes
The page content is not fully responsive on small screen devices. 
See: 
![image](https://user-images.githubusercontent.com/41796013/216837242-411796e4-ccd4-4511-8eec-376bc6e9df85.png)

make the text content to have max-width of `70-80`% according to design.

2023-02-06 04:31 UTC, niladrix719 commented
> The page content is not fully responsive on small screen devices. See: ![image](https://user-images.githubusercontent.com/41796013/216837242-411796e4-ccd4-4511-8eec-376bc6e9df85.png)
> 
> make the text content to have max-width of `70-80`% according to design.

made it responsive for smaller devices

2023-02-06 04:31 UTC, niladrix719 commented
@arpitghura made it responsive for smaller devices

2023-02-06 07:00 UTC, arpitghura approved these changes

2023-02-06 07:00 UTC, merged